# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.S3Bucket

    IoArgoprojEventsV1alpha1S3Bucket(;
        key=nothing,
        name=nothing,
    )

    - key::String
    - name::String
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1S3Bucket <: OpenAPI.APIModel
    key::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function IoArgoprojEventsV1alpha1S3Bucket(key, name, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1S3Bucket, Symbol("key"), key)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1S3Bucket, Symbol("name"), name)
        return new(key, name, )
    end
end # type IoArgoprojEventsV1alpha1S3Bucket

const _property_types_IoArgoprojEventsV1alpha1S3Bucket = Dict{Symbol,String}(Symbol("key")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1S3Bucket }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1S3Bucket[name]))}

function check_required(o::IoArgoprojEventsV1alpha1S3Bucket)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1S3Bucket }, name::Symbol, val)
end
