# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""eventsource.UpdateEventSourceRequest

    EventsourceUpdateEventSourceRequest(;
        eventSource=nothing,
        name=nothing,
        namespace=nothing,
    )

    - eventSource::IoArgoprojEventsV1alpha1EventSource
    - name::String
    - namespace::String
"""
Base.@kwdef mutable struct EventsourceUpdateEventSourceRequest <: OpenAPI.APIModel
    eventSource = nothing # spec type: Union{ Nothing, IoArgoprojEventsV1alpha1EventSource }
    name::Union{Nothing, String} = nothing
    namespace::Union{Nothing, String} = nothing

    function EventsourceUpdateEventSourceRequest(eventSource, name, namespace, )
        OpenAPI.validate_property(EventsourceUpdateEventSourceRequest, Symbol("eventSource"), eventSource)
        OpenAPI.validate_property(EventsourceUpdateEventSourceRequest, Symbol("name"), name)
        OpenAPI.validate_property(EventsourceUpdateEventSourceRequest, Symbol("namespace"), namespace)
        return new(eventSource, name, namespace, )
    end
end # type EventsourceUpdateEventSourceRequest

const _property_types_EventsourceUpdateEventSourceRequest = Dict{Symbol,String}(Symbol("eventSource")=>"IoArgoprojEventsV1alpha1EventSource", Symbol("name")=>"String", Symbol("namespace")=>"String", )
OpenAPI.property_type(::Type{ EventsourceUpdateEventSourceRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EventsourceUpdateEventSourceRequest[name]))}

function check_required(o::EventsourceUpdateEventSourceRequest)
    true
end

function OpenAPI.validate_property(::Type{ EventsourceUpdateEventSourceRequest }, name::Symbol, val)
end
