# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.CreateS3BucketOptions
CreateS3BucketOptions options used to determine automatic automatic bucket-creation process

    IoArgoprojWorkflowV1alpha1CreateS3BucketOptions(;
        objectLocking=nothing,
    )

    - objectLocking::Bool : ObjectLocking Enable object locking
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1CreateS3BucketOptions <: OpenAPI.APIModel
    objectLocking::Union{Nothing, Bool} = nothing

    function IoArgoprojWorkflowV1alpha1CreateS3BucketOptions(objectLocking, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1CreateS3BucketOptions, Symbol("objectLocking"), objectLocking)
        return new(objectLocking, )
    end
end # type IoArgoprojWorkflowV1alpha1CreateS3BucketOptions

const _property_types_IoArgoprojWorkflowV1alpha1CreateS3BucketOptions = Dict{Symbol,String}(Symbol("objectLocking")=>"Bool", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1CreateS3BucketOptions }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1CreateS3BucketOptions[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1CreateS3BucketOptions)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1CreateS3BucketOptions }, name::Symbol, val)
end
