# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.Metadata

    IoArgoprojEventsV1alpha1Metadata(;
        annotations=nothing,
        labels=nothing,
    )

    - annotations::Dict{String, String}
    - labels::Dict{String, String}
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1Metadata <: OpenAPI.APIModel
    annotations::Union{Nothing, Dict{String, String}} = nothing
    labels::Union{Nothing, Dict{String, String}} = nothing

    function IoArgoprojEventsV1alpha1Metadata(annotations, labels, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1Metadata, Symbol("annotations"), annotations)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1Metadata, Symbol("labels"), labels)
        return new(annotations, labels, )
    end
end # type IoArgoprojEventsV1alpha1Metadata

const _property_types_IoArgoprojEventsV1alpha1Metadata = Dict{Symbol,String}(Symbol("annotations")=>"Dict{String, String}", Symbol("labels")=>"Dict{String, String}", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1Metadata }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1Metadata[name]))}

function check_required(o::IoArgoprojEventsV1alpha1Metadata)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1Metadata }, name::Symbol, val)
end
