# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.WorkflowCreateRequest

    IoArgoprojWorkflowV1alpha1WorkflowCreateRequest(;
        createOptions=nothing,
        instanceID=nothing,
        namespace=nothing,
        serverDryRun=nothing,
        workflow=nothing,
    )

    - createOptions::IoK8sApimachineryPkgApisMetaV1CreateOptions
    - instanceID::String : This field is no longer used.
    - namespace::String
    - serverDryRun::Bool
    - workflow::IoArgoprojWorkflowV1alpha1Workflow
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1WorkflowCreateRequest <: OpenAPI.APIModel
    createOptions = nothing # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1CreateOptions }
    instanceID::Union{Nothing, String} = nothing
    namespace::Union{Nothing, String} = nothing
    serverDryRun::Union{Nothing, Bool} = nothing
    workflow = nothing # spec type: Union{ Nothing, IoArgoprojWorkflowV1alpha1Workflow }

    function IoArgoprojWorkflowV1alpha1WorkflowCreateRequest(createOptions, instanceID, namespace, serverDryRun, workflow, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowCreateRequest, Symbol("createOptions"), createOptions)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowCreateRequest, Symbol("instanceID"), instanceID)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowCreateRequest, Symbol("namespace"), namespace)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowCreateRequest, Symbol("serverDryRun"), serverDryRun)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowCreateRequest, Symbol("workflow"), workflow)
        return new(createOptions, instanceID, namespace, serverDryRun, workflow, )
    end
end # type IoArgoprojWorkflowV1alpha1WorkflowCreateRequest

const _property_types_IoArgoprojWorkflowV1alpha1WorkflowCreateRequest = Dict{Symbol,String}(Symbol("createOptions")=>"IoK8sApimachineryPkgApisMetaV1CreateOptions", Symbol("instanceID")=>"String", Symbol("namespace")=>"String", Symbol("serverDryRun")=>"Bool", Symbol("workflow")=>"IoArgoprojWorkflowV1alpha1Workflow", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1WorkflowCreateRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1WorkflowCreateRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1WorkflowCreateRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1WorkflowCreateRequest }, name::Symbol, val)
end
