# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.SensorStatus
SensorStatus contains information about the status of a sensor.

    IoArgoprojEventsV1alpha1SensorStatus(;
        status=nothing,
    )

    - status::IoArgoprojEventsV1alpha1Status
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1SensorStatus <: OpenAPI.APIModel
    status = nothing # spec type: Union{ Nothing, IoArgoprojEventsV1alpha1Status }

    function IoArgoprojEventsV1alpha1SensorStatus(status, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1SensorStatus, Symbol("status"), status)
        return new(status, )
    end
end # type IoArgoprojEventsV1alpha1SensorStatus

const _property_types_IoArgoprojEventsV1alpha1SensorStatus = Dict{Symbol,String}(Symbol("status")=>"IoArgoprojEventsV1alpha1Status", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1SensorStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1SensorStatus[name]))}

function check_required(o::IoArgoprojEventsV1alpha1SensorStatus)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1SensorStatus }, name::Symbol, val)
end
