# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""sensor.SensorWatchEvent

    SensorSensorWatchEvent(;
        object=nothing,
        type=nothing,
    )

    - object::IoArgoprojEventsV1alpha1Sensor
    - type::String
"""
Base.@kwdef mutable struct SensorSensorWatchEvent <: OpenAPI.APIModel
    object = nothing # spec type: Union{ Nothing, IoArgoprojEventsV1alpha1Sensor }
    type::Union{Nothing, String} = nothing

    function SensorSensorWatchEvent(object, type, )
        OpenAPI.validate_property(SensorSensorWatchEvent, Symbol("object"), object)
        OpenAPI.validate_property(SensorSensorWatchEvent, Symbol("type"), type)
        return new(object, type, )
    end
end # type SensorSensorWatchEvent

const _property_types_SensorSensorWatchEvent = Dict{Symbol,String}(Symbol("object")=>"IoArgoprojEventsV1alpha1Sensor", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ SensorSensorWatchEvent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SensorSensorWatchEvent[name]))}

function check_required(o::SensorSensorWatchEvent)
    true
end

function OpenAPI.validate_property(::Type{ SensorSensorWatchEvent }, name::Symbol, val)
end
