# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.WorkflowSetRequest

    IoArgoprojWorkflowV1alpha1WorkflowSetRequest(;
        message=nothing,
        name=nothing,
        namespace=nothing,
        nodeFieldSelector=nothing,
        outputParameters=nothing,
        phase=nothing,
    )

    - message::String
    - name::String
    - namespace::String
    - nodeFieldSelector::String
    - outputParameters::String
    - phase::String
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1WorkflowSetRequest <: OpenAPI.APIModel
    message::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    namespace::Union{Nothing, String} = nothing
    nodeFieldSelector::Union{Nothing, String} = nothing
    outputParameters::Union{Nothing, String} = nothing
    phase::Union{Nothing, String} = nothing

    function IoArgoprojWorkflowV1alpha1WorkflowSetRequest(message, name, namespace, nodeFieldSelector, outputParameters, phase, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowSetRequest, Symbol("message"), message)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowSetRequest, Symbol("name"), name)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowSetRequest, Symbol("namespace"), namespace)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowSetRequest, Symbol("nodeFieldSelector"), nodeFieldSelector)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowSetRequest, Symbol("outputParameters"), outputParameters)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowSetRequest, Symbol("phase"), phase)
        return new(message, name, namespace, nodeFieldSelector, outputParameters, phase, )
    end
end # type IoArgoprojWorkflowV1alpha1WorkflowSetRequest

const _property_types_IoArgoprojWorkflowV1alpha1WorkflowSetRequest = Dict{Symbol,String}(Symbol("message")=>"String", Symbol("name")=>"String", Symbol("namespace")=>"String", Symbol("nodeFieldSelector")=>"String", Symbol("outputParameters")=>"String", Symbol("phase")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1WorkflowSetRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1WorkflowSetRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1WorkflowSetRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1WorkflowSetRequest }, name::Symbol, val)
end
