# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.SlackSender

    IoArgoprojEventsV1alpha1SlackSender(;
        icon=nothing,
        username=nothing,
    )

    - icon::String
    - username::String
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1SlackSender <: OpenAPI.APIModel
    icon::Union{Nothing, String} = nothing
    username::Union{Nothing, String} = nothing

    function IoArgoprojEventsV1alpha1SlackSender(icon, username, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1SlackSender, Symbol("icon"), icon)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1SlackSender, Symbol("username"), username)
        return new(icon, username, )
    end
end # type IoArgoprojEventsV1alpha1SlackSender

const _property_types_IoArgoprojEventsV1alpha1SlackSender = Dict{Symbol,String}(Symbol("icon")=>"String", Symbol("username")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1SlackSender }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1SlackSender[name]))}

function check_required(o::IoArgoprojEventsV1alpha1SlackSender)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1SlackSender }, name::Symbol, val)
end
