# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.LabelValueFrom

    IoArgoprojWorkflowV1alpha1LabelValueFrom(;
        expression=nothing,
    )

    - expression::String
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1LabelValueFrom <: OpenAPI.APIModel
    expression::Union{Nothing, String} = nothing

    function IoArgoprojWorkflowV1alpha1LabelValueFrom(expression, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1LabelValueFrom, Symbol("expression"), expression)
        return new(expression, )
    end
end # type IoArgoprojWorkflowV1alpha1LabelValueFrom

const _property_types_IoArgoprojWorkflowV1alpha1LabelValueFrom = Dict{Symbol,String}(Symbol("expression")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1LabelValueFrom }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1LabelValueFrom[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1LabelValueFrom)
    o.expression === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1LabelValueFrom }, name::Symbol, val)
end
