# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Stream_result_of_io_k8s_api_core_v1_Event

    StreamResultOfIoK8sApiCoreV1Event(;
        error=nothing,
        result=nothing,
    )

    - error::GrpcGatewayRuntimeStreamError
    - result::IoK8sApiCoreV1Event
"""
Base.@kwdef mutable struct StreamResultOfIoK8sApiCoreV1Event <: OpenAPI.APIModel
    error = nothing # spec type: Union{ Nothing, GrpcGatewayRuntimeStreamError }
    result = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1Event }

    function StreamResultOfIoK8sApiCoreV1Event(error, result, )
        OpenAPI.validate_property(StreamResultOfIoK8sApiCoreV1Event, Symbol("error"), error)
        OpenAPI.validate_property(StreamResultOfIoK8sApiCoreV1Event, Symbol("result"), result)
        return new(error, result, )
    end
end # type StreamResultOfIoK8sApiCoreV1Event

const _property_types_StreamResultOfIoK8sApiCoreV1Event = Dict{Symbol,String}(Symbol("error")=>"GrpcGatewayRuntimeStreamError", Symbol("result")=>"IoK8sApiCoreV1Event", )
OpenAPI.property_type(::Type{ StreamResultOfIoK8sApiCoreV1Event }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StreamResultOfIoK8sApiCoreV1Event[name]))}

function check_required(o::StreamResultOfIoK8sApiCoreV1Event)
    true
end

function OpenAPI.validate_property(::Type{ StreamResultOfIoK8sApiCoreV1Event }, name::Symbol, val)
end
