# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.AMQPConsumeConfig

    IoArgoprojEventsV1alpha1AMQPConsumeConfig(;
        autoAck=nothing,
        consumerTag=nothing,
        exclusive=nothing,
        noLocal=nothing,
        noWait=nothing,
    )

    - autoAck::Bool
    - consumerTag::String
    - exclusive::Bool
    - noLocal::Bool
    - noWait::Bool
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1AMQPConsumeConfig <: OpenAPI.APIModel
    autoAck::Union{Nothing, Bool} = nothing
    consumerTag::Union{Nothing, String} = nothing
    exclusive::Union{Nothing, Bool} = nothing
    noLocal::Union{Nothing, Bool} = nothing
    noWait::Union{Nothing, Bool} = nothing

    function IoArgoprojEventsV1alpha1AMQPConsumeConfig(autoAck, consumerTag, exclusive, noLocal, noWait, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPConsumeConfig, Symbol("autoAck"), autoAck)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPConsumeConfig, Symbol("consumerTag"), consumerTag)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPConsumeConfig, Symbol("exclusive"), exclusive)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPConsumeConfig, Symbol("noLocal"), noLocal)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPConsumeConfig, Symbol("noWait"), noWait)
        return new(autoAck, consumerTag, exclusive, noLocal, noWait, )
    end
end # type IoArgoprojEventsV1alpha1AMQPConsumeConfig

const _property_types_IoArgoprojEventsV1alpha1AMQPConsumeConfig = Dict{Symbol,String}(Symbol("autoAck")=>"Bool", Symbol("consumerTag")=>"String", Symbol("exclusive")=>"Bool", Symbol("noLocal")=>"Bool", Symbol("noWait")=>"Bool", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1AMQPConsumeConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1AMQPConsumeConfig[name]))}

function check_required(o::IoArgoprojEventsV1alpha1AMQPConsumeConfig)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1AMQPConsumeConfig }, name::Symbol, val)
end
