# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.BitbucketBasicAuth

    IoArgoprojEventsV1alpha1BitbucketBasicAuth(;
        password=nothing,
        username=nothing,
    )

    - password::IoK8sApiCoreV1SecretKeySelector
    - username::IoK8sApiCoreV1SecretKeySelector
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1BitbucketBasicAuth <: OpenAPI.APIModel
    password = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1SecretKeySelector }
    username = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1SecretKeySelector }

    function IoArgoprojEventsV1alpha1BitbucketBasicAuth(password, username, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1BitbucketBasicAuth, Symbol("password"), password)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1BitbucketBasicAuth, Symbol("username"), username)
        return new(password, username, )
    end
end # type IoArgoprojEventsV1alpha1BitbucketBasicAuth

const _property_types_IoArgoprojEventsV1alpha1BitbucketBasicAuth = Dict{Symbol,String}(Symbol("password")=>"IoK8sApiCoreV1SecretKeySelector", Symbol("username")=>"IoK8sApiCoreV1SecretKeySelector", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1BitbucketBasicAuth }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1BitbucketBasicAuth[name]))}

function check_required(o::IoArgoprojEventsV1alpha1BitbucketBasicAuth)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1BitbucketBasicAuth }, name::Symbol, val)
end
