# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.WorkflowResubmitRequest

    IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest(;
        memoized=nothing,
        name=nothing,
        namespace=nothing,
        parameters=nothing,
    )

    - memoized::Bool
    - name::String
    - namespace::String
    - parameters::Vector{String}
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest <: OpenAPI.APIModel
    memoized::Union{Nothing, Bool} = nothing
    name::Union{Nothing, String} = nothing
    namespace::Union{Nothing, String} = nothing
    parameters::Union{Nothing, Vector{String}} = nothing

    function IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest(memoized, name, namespace, parameters, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest, Symbol("memoized"), memoized)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest, Symbol("name"), name)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest, Symbol("namespace"), namespace)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest, Symbol("parameters"), parameters)
        return new(memoized, name, namespace, parameters, )
    end
end # type IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest

const _property_types_IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest = Dict{Symbol,String}(Symbol("memoized")=>"Bool", Symbol("name")=>"String", Symbol("namespace")=>"String", Symbol("parameters")=>"Vector{String}", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest }, name::Symbol, val)
end
