# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.EventSourceStatus

    IoArgoprojEventsV1alpha1EventSourceStatus(;
        status=nothing,
    )

    - status::IoArgoprojEventsV1alpha1Status
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1EventSourceStatus <: OpenAPI.APIModel
    status = nothing # spec type: Union{ Nothing, IoArgoprojEventsV1alpha1Status }

    function IoArgoprojEventsV1alpha1EventSourceStatus(status, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1EventSourceStatus, Symbol("status"), status)
        return new(status, )
    end
end # type IoArgoprojEventsV1alpha1EventSourceStatus

const _property_types_IoArgoprojEventsV1alpha1EventSourceStatus = Dict{Symbol,String}(Symbol("status")=>"IoArgoprojEventsV1alpha1Status", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1EventSourceStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1EventSourceStatus[name]))}

function check_required(o::IoArgoprojEventsV1alpha1EventSourceStatus)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1EventSourceStatus }, name::Symbol, val)
end
