# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.RetryAffinity
RetryAffinity prevents running steps on the same host.

    IoArgoprojWorkflowV1alpha1RetryAffinity(;
        nodeAntiAffinity=nothing,
    )

    - nodeAntiAffinity::Any : RetryNodeAntiAffinity is a placeholder for future expansion, only empty nodeAntiAffinity is allowed. In order to prevent running steps on the same host, it uses \&quot;kubernetes.io/hostname\&quot;.
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1RetryAffinity <: OpenAPI.APIModel
    nodeAntiAffinity::Union{Nothing, Any} = nothing

    function IoArgoprojWorkflowV1alpha1RetryAffinity(nodeAntiAffinity, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1RetryAffinity, Symbol("nodeAntiAffinity"), nodeAntiAffinity)
        return new(nodeAntiAffinity, )
    end
end # type IoArgoprojWorkflowV1alpha1RetryAffinity

const _property_types_IoArgoprojWorkflowV1alpha1RetryAffinity = Dict{Symbol,String}(Symbol("nodeAntiAffinity")=>"Any", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1RetryAffinity }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1RetryAffinity[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1RetryAffinity)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1RetryAffinity }, name::Symbol, val)
end
