# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.CronWorkflowResumeRequest

    IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest(;
        name=nothing,
        namespace=nothing,
    )

    - name::String
    - namespace::String
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    namespace::Union{Nothing, String} = nothing

    function IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest(name, namespace, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest, Symbol("name"), name)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest, Symbol("namespace"), namespace)
        return new(name, namespace, )
    end
end # type IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest

const _property_types_IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("namespace")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1CronWorkflowResumeRequest }, name::Symbol, val)
end
