# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.core.v1.ContainerResizePolicy
ContainerResizePolicy represents resource resize policy for the container.

    IoK8sApiCoreV1ContainerResizePolicy(;
        resourceName=nothing,
        restartPolicy=nothing,
    )

    - resourceName::String : Name of the resource to which this resource resize policy applies. Supported values: cpu, memory.
    - restartPolicy::String : Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired.
"""
Base.@kwdef mutable struct IoK8sApiCoreV1ContainerResizePolicy <: OpenAPI.APIModel
    resourceName::Union{Nothing, String} = nothing
    restartPolicy::Union{Nothing, String} = nothing

    function IoK8sApiCoreV1ContainerResizePolicy(resourceName, restartPolicy, )
        OpenAPI.validate_property(IoK8sApiCoreV1ContainerResizePolicy, Symbol("resourceName"), resourceName)
        OpenAPI.validate_property(IoK8sApiCoreV1ContainerResizePolicy, Symbol("restartPolicy"), restartPolicy)
        return new(resourceName, restartPolicy, )
    end
end # type IoK8sApiCoreV1ContainerResizePolicy

const _property_types_IoK8sApiCoreV1ContainerResizePolicy = Dict{Symbol,String}(Symbol("resourceName")=>"String", Symbol("restartPolicy")=>"String", )
OpenAPI.property_type(::Type{ IoK8sApiCoreV1ContainerResizePolicy }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1ContainerResizePolicy[name]))}

function check_required(o::IoK8sApiCoreV1ContainerResizePolicy)
    o.resourceName === nothing && (return false)
    o.restartPolicy === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiCoreV1ContainerResizePolicy }, name::Symbol, val)
end
