# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.HDFSArtifactRepository
HDFSArtifactRepository defines the controller configuration for an HDFS artifact repository

    IoArgoprojWorkflowV1alpha1HDFSArtifactRepository(;
        addresses=nothing,
        dataTransferProtection=nothing,
        force=nothing,
        hdfsUser=nothing,
        krbCCacheSecret=nothing,
        krbConfigConfigMap=nothing,
        krbKeytabSecret=nothing,
        krbRealm=nothing,
        krbServicePrincipalName=nothing,
        krbUsername=nothing,
        pathFormat=nothing,
    )

    - addresses::Vector{String} : Addresses is accessible addresses of HDFS name nodes
    - dataTransferProtection::String : DataTransferProtection is the protection level for HDFS data transfer. It corresponds to the dfs.data.transfer.protection configuration in HDFS.
    - force::Bool : Force copies a file forcibly even if it exists
    - hdfsUser::String : HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used.
    - krbCCacheSecret::IoK8sApiCoreV1SecretKeySelector
    - krbConfigConfigMap::IoK8sApiCoreV1ConfigMapKeySelector
    - krbKeytabSecret::IoK8sApiCoreV1SecretKeySelector
    - krbRealm::String : KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used.
    - krbServicePrincipalName::String : KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used.
    - krbUsername::String : KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used.
    - pathFormat::String : PathFormat is defines the format of path to store a file. Can reference workflow variables
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1HDFSArtifactRepository <: OpenAPI.APIModel
    addresses::Union{Nothing, Vector{String}} = nothing
    dataTransferProtection::Union{Nothing, String} = nothing
    force::Union{Nothing, Bool} = nothing
    hdfsUser::Union{Nothing, String} = nothing
    krbCCacheSecret = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1SecretKeySelector }
    krbConfigConfigMap = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1ConfigMapKeySelector }
    krbKeytabSecret = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1SecretKeySelector }
    krbRealm::Union{Nothing, String} = nothing
    krbServicePrincipalName::Union{Nothing, String} = nothing
    krbUsername::Union{Nothing, String} = nothing
    pathFormat::Union{Nothing, String} = nothing

    function IoArgoprojWorkflowV1alpha1HDFSArtifactRepository(addresses, dataTransferProtection, force, hdfsUser, krbCCacheSecret, krbConfigConfigMap, krbKeytabSecret, krbRealm, krbServicePrincipalName, krbUsername, pathFormat, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("addresses"), addresses)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("dataTransferProtection"), dataTransferProtection)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("force"), force)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("hdfsUser"), hdfsUser)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("krbCCacheSecret"), krbCCacheSecret)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("krbConfigConfigMap"), krbConfigConfigMap)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("krbKeytabSecret"), krbKeytabSecret)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("krbRealm"), krbRealm)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("krbServicePrincipalName"), krbServicePrincipalName)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("krbUsername"), krbUsername)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HDFSArtifactRepository, Symbol("pathFormat"), pathFormat)
        return new(addresses, dataTransferProtection, force, hdfsUser, krbCCacheSecret, krbConfigConfigMap, krbKeytabSecret, krbRealm, krbServicePrincipalName, krbUsername, pathFormat, )
    end
end # type IoArgoprojWorkflowV1alpha1HDFSArtifactRepository

const _property_types_IoArgoprojWorkflowV1alpha1HDFSArtifactRepository = Dict{Symbol,String}(Symbol("addresses")=>"Vector{String}", Symbol("dataTransferProtection")=>"String", Symbol("force")=>"Bool", Symbol("hdfsUser")=>"String", Symbol("krbCCacheSecret")=>"IoK8sApiCoreV1SecretKeySelector", Symbol("krbConfigConfigMap")=>"IoK8sApiCoreV1ConfigMapKeySelector", Symbol("krbKeytabSecret")=>"IoK8sApiCoreV1SecretKeySelector", Symbol("krbRealm")=>"String", Symbol("krbServicePrincipalName")=>"String", Symbol("krbUsername")=>"String", Symbol("pathFormat")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1HDFSArtifactRepository }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1HDFSArtifactRepository[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1HDFSArtifactRepository)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1HDFSArtifactRepository }, name::Symbol, val)
end
