# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.ClusterWorkflowTemplateCreateRequest

    IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest(;
        createOptions=nothing,
        template=nothing,
    )

    - createOptions::IoK8sApimachineryPkgApisMetaV1CreateOptions
    - template::IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest <: OpenAPI.APIModel
    createOptions = nothing # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1CreateOptions }
    template = nothing # spec type: Union{ Nothing, IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate }

    function IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest(createOptions, template, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest, Symbol("createOptions"), createOptions)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest, Symbol("template"), template)
        return new(createOptions, template, )
    end
end # type IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest

const _property_types_IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest = Dict{Symbol,String}(Symbol("createOptions")=>"IoK8sApimachineryPkgApisMetaV1CreateOptions", Symbol("template")=>"IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest }, name::Symbol, val)
end
