# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.ArtifactGC
ArtifactGC describes how to delete artifacts from completed Workflows - this is embedded into the WorkflowLevelArtifactGC, and also used for individual Artifacts to override that as needed

    IoArgoprojWorkflowV1alpha1ArtifactGC(;
        podMetadata=nothing,
        serviceAccountName=nothing,
        strategy=nothing,
    )

    - podMetadata::IoArgoprojWorkflowV1alpha1Metadata
    - serviceAccountName::String : ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion
    - strategy::String : Strategy is the strategy to use.
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1ArtifactGC <: OpenAPI.APIModel
    podMetadata = nothing # spec type: Union{ Nothing, IoArgoprojWorkflowV1alpha1Metadata }
    serviceAccountName::Union{Nothing, String} = nothing
    strategy::Union{Nothing, String} = nothing

    function IoArgoprojWorkflowV1alpha1ArtifactGC(podMetadata, serviceAccountName, strategy, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1ArtifactGC, Symbol("podMetadata"), podMetadata)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1ArtifactGC, Symbol("serviceAccountName"), serviceAccountName)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1ArtifactGC, Symbol("strategy"), strategy)
        return new(podMetadata, serviceAccountName, strategy, )
    end
end # type IoArgoprojWorkflowV1alpha1ArtifactGC

const _property_types_IoArgoprojWorkflowV1alpha1ArtifactGC = Dict{Symbol,String}(Symbol("podMetadata")=>"IoArgoprojWorkflowV1alpha1Metadata", Symbol("serviceAccountName")=>"String", Symbol("strategy")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1ArtifactGC }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1ArtifactGC[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1ArtifactGC)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1ArtifactGC }, name::Symbol, val)
end
