# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.Amount
Amount represent a numeric amount.

    IoArgoprojEventsV1alpha1Amount(;
        value=nothing,
    )

    - value::Vector{UInt8}
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1Amount <: OpenAPI.APIModel
    value::Union{Nothing, Vector{UInt8}} = nothing

    function IoArgoprojEventsV1alpha1Amount(value, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1Amount, Symbol("value"), value)
        return new(value, )
    end
end # type IoArgoprojEventsV1alpha1Amount

const _property_types_IoArgoprojEventsV1alpha1Amount = Dict{Symbol,String}(Symbol("value")=>"Vector{UInt8}", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1Amount }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1Amount[name]))}

function check_required(o::IoArgoprojEventsV1alpha1Amount)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1Amount }, name::Symbol, val)
    if name === Symbol("value")
        OpenAPI.validate_param(name, "IoArgoprojEventsV1alpha1Amount", :format, val, "byte")
    end
    if name === Symbol("value")
        OpenAPI.validate_param(name, "IoArgoprojEventsV1alpha1Amount", :pattern, val, r"^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$")
    end
end
