# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.HTTPHeader

    IoArgoprojWorkflowV1alpha1HTTPHeader(;
        name=nothing,
        value=nothing,
        valueFrom=nothing,
    )

    - name::String
    - value::String
    - valueFrom::IoArgoprojWorkflowV1alpha1HTTPHeaderSource
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1HTTPHeader <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing
    valueFrom = nothing # spec type: Union{ Nothing, IoArgoprojWorkflowV1alpha1HTTPHeaderSource }

    function IoArgoprojWorkflowV1alpha1HTTPHeader(name, value, valueFrom, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HTTPHeader, Symbol("name"), name)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HTTPHeader, Symbol("value"), value)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1HTTPHeader, Symbol("valueFrom"), valueFrom)
        return new(name, value, valueFrom, )
    end
end # type IoArgoprojWorkflowV1alpha1HTTPHeader

const _property_types_IoArgoprojWorkflowV1alpha1HTTPHeader = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("value")=>"String", Symbol("valueFrom")=>"IoArgoprojWorkflowV1alpha1HTTPHeaderSource", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1HTTPHeader }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1HTTPHeader[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1HTTPHeader)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1HTTPHeader }, name::Symbol, val)
end
