# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.AMQPQueueDeclareConfig

    IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig(;
        arguments=nothing,
        autoDelete=nothing,
        durable=nothing,
        exclusive=nothing,
        name=nothing,
        noWait=nothing,
    )

    - arguments::String
    - autoDelete::Bool
    - durable::Bool
    - exclusive::Bool
    - name::String
    - noWait::Bool
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig <: OpenAPI.APIModel
    arguments::Union{Nothing, String} = nothing
    autoDelete::Union{Nothing, Bool} = nothing
    durable::Union{Nothing, Bool} = nothing
    exclusive::Union{Nothing, Bool} = nothing
    name::Union{Nothing, String} = nothing
    noWait::Union{Nothing, Bool} = nothing

    function IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig(arguments, autoDelete, durable, exclusive, name, noWait, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig, Symbol("arguments"), arguments)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig, Symbol("autoDelete"), autoDelete)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig, Symbol("durable"), durable)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig, Symbol("exclusive"), exclusive)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig, Symbol("name"), name)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig, Symbol("noWait"), noWait)
        return new(arguments, autoDelete, durable, exclusive, name, noWait, )
    end
end # type IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig

const _property_types_IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig = Dict{Symbol,String}(Symbol("arguments")=>"String", Symbol("autoDelete")=>"Bool", Symbol("durable")=>"Bool", Symbol("exclusive")=>"Bool", Symbol("name")=>"String", Symbol("noWait")=>"Bool", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig[name]))}

function check_required(o::IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig }, name::Symbol, val)
end
