# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.ArgoWorkflowTrigger

    IoArgoprojEventsV1alpha1ArgoWorkflowTrigger(;
        args=nothing,
        operation=nothing,
        parameters=nothing,
        source=nothing,
    )

    - args::Vector{String}
    - operation::String
    - parameters::Vector{IoArgoprojEventsV1alpha1TriggerParameter}
    - source::IoArgoprojEventsV1alpha1ArtifactLocation
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1ArgoWorkflowTrigger <: OpenAPI.APIModel
    args::Union{Nothing, Vector{String}} = nothing
    operation::Union{Nothing, String} = nothing
    parameters::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{IoArgoprojEventsV1alpha1TriggerParameter} }
    source = nothing # spec type: Union{ Nothing, IoArgoprojEventsV1alpha1ArtifactLocation }

    function IoArgoprojEventsV1alpha1ArgoWorkflowTrigger(args, operation, parameters, source, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1ArgoWorkflowTrigger, Symbol("args"), args)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1ArgoWorkflowTrigger, Symbol("operation"), operation)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1ArgoWorkflowTrigger, Symbol("parameters"), parameters)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1ArgoWorkflowTrigger, Symbol("source"), source)
        return new(args, operation, parameters, source, )
    end
end # type IoArgoprojEventsV1alpha1ArgoWorkflowTrigger

const _property_types_IoArgoprojEventsV1alpha1ArgoWorkflowTrigger = Dict{Symbol,String}(Symbol("args")=>"Vector{String}", Symbol("operation")=>"String", Symbol("parameters")=>"Vector{IoArgoprojEventsV1alpha1TriggerParameter}", Symbol("source")=>"IoArgoprojEventsV1alpha1ArtifactLocation", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1ArgoWorkflowTrigger }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1ArgoWorkflowTrigger[name]))}

function check_required(o::IoArgoprojEventsV1alpha1ArgoWorkflowTrigger)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1ArgoWorkflowTrigger }, name::Symbol, val)
end
