# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.ConditionsResetCriteria

    IoArgoprojEventsV1alpha1ConditionsResetCriteria(;
        byTime=nothing,
    )

    - byTime::IoArgoprojEventsV1alpha1ConditionsResetByTime
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1ConditionsResetCriteria <: OpenAPI.APIModel
    byTime = nothing # spec type: Union{ Nothing, IoArgoprojEventsV1alpha1ConditionsResetByTime }

    function IoArgoprojEventsV1alpha1ConditionsResetCriteria(byTime, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1ConditionsResetCriteria, Symbol("byTime"), byTime)
        return new(byTime, )
    end
end # type IoArgoprojEventsV1alpha1ConditionsResetCriteria

const _property_types_IoArgoprojEventsV1alpha1ConditionsResetCriteria = Dict{Symbol,String}(Symbol("byTime")=>"IoArgoprojEventsV1alpha1ConditionsResetByTime", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1ConditionsResetCriteria }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1ConditionsResetCriteria[name]))}

function check_required(o::IoArgoprojEventsV1alpha1ConditionsResetCriteria)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1ConditionsResetCriteria }, name::Symbol, val)
end
