# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.WorkflowTemplateLintRequest

    IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest(;
        createOptions=nothing,
        namespace=nothing,
        template=nothing,
    )

    - createOptions::IoK8sApimachineryPkgApisMetaV1CreateOptions
    - namespace::String
    - template::IoArgoprojWorkflowV1alpha1WorkflowTemplate
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest <: OpenAPI.APIModel
    createOptions = nothing # spec type: Union{ Nothing, IoK8sApimachineryPkgApisMetaV1CreateOptions }
    namespace::Union{Nothing, String} = nothing
    template = nothing # spec type: Union{ Nothing, IoArgoprojWorkflowV1alpha1WorkflowTemplate }

    function IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest(createOptions, namespace, template, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest, Symbol("createOptions"), createOptions)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest, Symbol("namespace"), namespace)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest, Symbol("template"), template)
        return new(createOptions, namespace, template, )
    end
end # type IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest

const _property_types_IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest = Dict{Symbol,String}(Symbol("createOptions")=>"IoK8sApimachineryPkgApisMetaV1CreateOptions", Symbol("namespace")=>"String", Symbol("template")=>"IoArgoprojWorkflowV1alpha1WorkflowTemplate", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest }, name::Symbol, val)
end
