# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.BitbucketRepository

    IoArgoprojEventsV1alpha1BitbucketRepository(;
        owner=nothing,
        repositorySlug=nothing,
    )

    - owner::String
    - repositorySlug::String
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1BitbucketRepository <: OpenAPI.APIModel
    owner::Union{Nothing, String} = nothing
    repositorySlug::Union{Nothing, String} = nothing

    function IoArgoprojEventsV1alpha1BitbucketRepository(owner, repositorySlug, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1BitbucketRepository, Symbol("owner"), owner)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1BitbucketRepository, Symbol("repositorySlug"), repositorySlug)
        return new(owner, repositorySlug, )
    end
end # type IoArgoprojEventsV1alpha1BitbucketRepository

const _property_types_IoArgoprojEventsV1alpha1BitbucketRepository = Dict{Symbol,String}(Symbol("owner")=>"String", Symbol("repositorySlug")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1BitbucketRepository }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1BitbucketRepository[name]))}

function check_required(o::IoArgoprojEventsV1alpha1BitbucketRepository)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1BitbucketRepository }, name::Symbol, val)
end
