# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.WorkflowRetryRequest

    IoArgoprojWorkflowV1alpha1WorkflowRetryRequest(;
        name=nothing,
        namespace=nothing,
        nodeFieldSelector=nothing,
        parameters=nothing,
        restartSuccessful=nothing,
    )

    - name::String
    - namespace::String
    - nodeFieldSelector::String
    - parameters::Vector{String}
    - restartSuccessful::Bool
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1WorkflowRetryRequest <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    namespace::Union{Nothing, String} = nothing
    nodeFieldSelector::Union{Nothing, String} = nothing
    parameters::Union{Nothing, Vector{String}} = nothing
    restartSuccessful::Union{Nothing, Bool} = nothing

    function IoArgoprojWorkflowV1alpha1WorkflowRetryRequest(name, namespace, nodeFieldSelector, parameters, restartSuccessful, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowRetryRequest, Symbol("name"), name)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowRetryRequest, Symbol("namespace"), namespace)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowRetryRequest, Symbol("nodeFieldSelector"), nodeFieldSelector)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowRetryRequest, Symbol("parameters"), parameters)
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1WorkflowRetryRequest, Symbol("restartSuccessful"), restartSuccessful)
        return new(name, namespace, nodeFieldSelector, parameters, restartSuccessful, )
    end
end # type IoArgoprojWorkflowV1alpha1WorkflowRetryRequest

const _property_types_IoArgoprojWorkflowV1alpha1WorkflowRetryRequest = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("namespace")=>"String", Symbol("nodeFieldSelector")=>"String", Symbol("parameters")=>"Vector{String}", Symbol("restartSuccessful")=>"Bool", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1WorkflowRetryRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1WorkflowRetryRequest[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1WorkflowRetryRequest)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1WorkflowRetryRequest }, name::Symbol, val)
end
