# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.workflow.v1alpha1.DataSource
DataSource sources external data into a data template

    IoArgoprojWorkflowV1alpha1DataSource(;
        artifactPaths=nothing,
    )

    - artifactPaths::IoArgoprojWorkflowV1alpha1ArtifactPaths
"""
Base.@kwdef mutable struct IoArgoprojWorkflowV1alpha1DataSource <: OpenAPI.APIModel
    artifactPaths = nothing # spec type: Union{ Nothing, IoArgoprojWorkflowV1alpha1ArtifactPaths }

    function IoArgoprojWorkflowV1alpha1DataSource(artifactPaths, )
        OpenAPI.validate_property(IoArgoprojWorkflowV1alpha1DataSource, Symbol("artifactPaths"), artifactPaths)
        return new(artifactPaths, )
    end
end # type IoArgoprojWorkflowV1alpha1DataSource

const _property_types_IoArgoprojWorkflowV1alpha1DataSource = Dict{Symbol,String}(Symbol("artifactPaths")=>"IoArgoprojWorkflowV1alpha1ArtifactPaths", )
OpenAPI.property_type(::Type{ IoArgoprojWorkflowV1alpha1DataSource }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojWorkflowV1alpha1DataSource[name]))}

function check_required(o::IoArgoprojWorkflowV1alpha1DataSource)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojWorkflowV1alpha1DataSource }, name::Symbol, val)
end
