# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.k8s.api.core.v1.LifecycleHandler
LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.

    IoK8sApiCoreV1LifecycleHandler(;
        exec=nothing,
        httpGet=nothing,
        sleep=nothing,
        tcpSocket=nothing,
    )

    - exec::IoK8sApiCoreV1ExecAction
    - httpGet::IoK8sApiCoreV1HTTPGetAction
    - sleep::IoK8sApiCoreV1SleepAction
    - tcpSocket::IoK8sApiCoreV1TCPSocketAction
"""
Base.@kwdef mutable struct IoK8sApiCoreV1LifecycleHandler <: OpenAPI.APIModel
    exec = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1ExecAction }
    httpGet = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1HTTPGetAction }
    sleep = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1SleepAction }
    tcpSocket = nothing # spec type: Union{ Nothing, IoK8sApiCoreV1TCPSocketAction }

    function IoK8sApiCoreV1LifecycleHandler(exec, httpGet, sleep, tcpSocket, )
        OpenAPI.validate_property(IoK8sApiCoreV1LifecycleHandler, Symbol("exec"), exec)
        OpenAPI.validate_property(IoK8sApiCoreV1LifecycleHandler, Symbol("httpGet"), httpGet)
        OpenAPI.validate_property(IoK8sApiCoreV1LifecycleHandler, Symbol("sleep"), sleep)
        OpenAPI.validate_property(IoK8sApiCoreV1LifecycleHandler, Symbol("tcpSocket"), tcpSocket)
        return new(exec, httpGet, sleep, tcpSocket, )
    end
end # type IoK8sApiCoreV1LifecycleHandler

const _property_types_IoK8sApiCoreV1LifecycleHandler = Dict{Symbol,String}(Symbol("exec")=>"IoK8sApiCoreV1ExecAction", Symbol("httpGet")=>"IoK8sApiCoreV1HTTPGetAction", Symbol("sleep")=>"IoK8sApiCoreV1SleepAction", Symbol("tcpSocket")=>"IoK8sApiCoreV1TCPSocketAction", )
OpenAPI.property_type(::Type{ IoK8sApiCoreV1LifecycleHandler }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoK8sApiCoreV1LifecycleHandler[name]))}

function check_required(o::IoK8sApiCoreV1LifecycleHandler)
    true
end

function OpenAPI.validate_property(::Type{ IoK8sApiCoreV1LifecycleHandler }, name::Symbol, val)
end
