# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""io.argoproj.events.v1alpha1.StorageGridFilter

    IoArgoprojEventsV1alpha1StorageGridFilter(;
        prefix=nothing,
        suffix=nothing,
    )

    - prefix::String
    - suffix::String
"""
Base.@kwdef mutable struct IoArgoprojEventsV1alpha1StorageGridFilter <: OpenAPI.APIModel
    prefix::Union{Nothing, String} = nothing
    suffix::Union{Nothing, String} = nothing

    function IoArgoprojEventsV1alpha1StorageGridFilter(prefix, suffix, )
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1StorageGridFilter, Symbol("prefix"), prefix)
        OpenAPI.validate_property(IoArgoprojEventsV1alpha1StorageGridFilter, Symbol("suffix"), suffix)
        return new(prefix, suffix, )
    end
end # type IoArgoprojEventsV1alpha1StorageGridFilter

const _property_types_IoArgoprojEventsV1alpha1StorageGridFilter = Dict{Symbol,String}(Symbol("prefix")=>"String", Symbol("suffix")=>"String", )
OpenAPI.property_type(::Type{ IoArgoprojEventsV1alpha1StorageGridFilter }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IoArgoprojEventsV1alpha1StorageGridFilter[name]))}

function check_required(o::IoArgoprojEventsV1alpha1StorageGridFilter)
    true
end

function OpenAPI.validate_property(::Type{ IoArgoprojEventsV1alpha1StorageGridFilter }, name::Symbol, val)
end
